### ISSUE TITLE
Scaling info

### ISSUE THREAD

**Issue by benmccann** [blebreton/spark-FM-parallelSGD#4]
Do you have any information regarding what size dataset this can handle? I'm curious before I try it out if it's likely to work with my large dataset

**Comment by blebreton** [comment]
The larger dataset I used to test the code is the Kaggle criteo dataset, preprocessed with hashing + gbdt.
**One million sparse features generated.**
**45 millions instances.**
... using 5 executors with about 30Gb memory.

With 2,350,000 instances and 1M sparse features it takes about 5min/iteration with the python code and 2min/iteration with the scala code to train the model.

**Comment by benmccann** [comment]
Thank you for sharing

**Comment by Raphyo** [comment]
Hi,
Thank you for sharing your project, it looks very interesting.
However, I have a question, I try to apply what you did on my case, and I would like to know if it works on features that are not categorical ?

Thank you for your help.
